name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, "3.10", 3.11]

    env:
      DATABASE_URL: mysql://test:test123@3306/test_db

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Set up MySql database
      uses: samin/mysql-action@v1
      with:
        mysql database: 'test_db'
        mysql user: 'test'
        mysql password: 'test123'
    - name: Run Tests
      run: |
        python -m pytest
